### ISSUE TITLE
Help text in configurator

### ISSUE THREAD

**Issue by chrowe** [openpipekit/opk-cli--adafruit-io#1]
There are 2 options, Feed and Key, but it is not clear what format these should be in

![screen shot 2015-10-25 at 11 36 10 pm](https://cloud.githubusercontent.com/assets/240115/10720774/3c534660-7b71-11e5-9267-2be7bdde6cc1.png)

Looking in the cli --help I see
  --feed [feed id] Example: feed r-pi-temperature
  --key [x-aio-key] Example: 2d3be35cf8f613afa0d59f2240c00aedf8bdanb49

Would be nice to have this kind of help in the configurator

**Comment by rjcorwin** [comment]
RIP configurator
